=== A1500/cam/cam/WebContent/WEB-INF/classes/spconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:bsp:sp-federation:config:1.0"
	xmlns:sp="urn:bsp:sp-federation:config:1.0"
	elementFormDefault="unqualified" version="1.0">

	<complexType name="spconfigType">
		<sequence>
			<element name="defaultIDPEntityID" type="string" maxOccurs="1" minOccurs="1">
				<annotation>默认的IDP EntityID</annotation>
			</element>
			<element name="defaultBinding" type="string" maxOccurs="1" minOccurs="1">
				<annotation>该SP默认使用的binding</annotation>
			</element>

			<element name="integrationModel" type="string" maxOccurs="1" minOccurs="1">
				<annotation>客户端和被集成应用的衔接模式</annotation>
			</element>

			<element name="keystorePassword" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="samlhandlerGroup" type="sp:SamlhandlerGroupType" maxOccurs="1" minOccurs="1"></element>
			<element name="assertionValidator" type="sp:validatorType" maxOccurs="1" minOccurs="0"></element>
			<element name="responseValidator" type="sp:validatorType" maxOccurs="1" minOccurs="0"></element>
			<element name="class" type="sp:classType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="validatorType">
		<sequence>
			<element name="ref" type="sp:refType" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="SamlhandlerGroupType">
		<sequence>
			<element name="samlhandler" type="sp:SamlhandlerType" maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="SamlhandlerType">
		<complexContent>
			<extension base="sp:containsType"></extension>
		</complexContent>
		<attribute name="id" type="string"></attribute>
	</complexType>

	<!-- for 引用 -->
	<complexType name="containsType">
		<sequence>
			<element name="ref" type="sp:refType" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>
	</complexType>

	<complexType name="refType">
		<attribute name="name" type="string"></attribute>
	</complexType>
	<!--  -->

	<complexType name="classType">
		<sequence>
			<element name="property" type="sp:propertyType" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>
		<attribute name="class" type="string"></attribute>
	</complexType>


	<complexType name="propertyType">
		<sequence>
			<element name="ref" type="sp:refType" maxOccurs="1" minOccurs="0"></element>
			<element name="value" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="value" type="string"></attribute>
	</complexType>


	<element name="spconfig" type="sp:spconfigType"></element>

</schema>

=== A1500/cam/cam/src/spconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<sp:spconfig xmlns:sp="urn:bsp:sp-federation:config:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:bsp:sp-federation:config:1.0 spconfig.xsd ">
   <!-- 默认的IDP EntityID -->
  <defaultIDPEntityID>http://10.162.11.80:8082/bspcore1</defaultIDPEntityID>
   <!-- 该SP默认使用的binding -->
  <defaultBinding>urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST</defaultBinding>
  <!-- 客户端和被集成应用的衔接模式 -->
  <integrationModel>native</integrationModel>
  <excludeFilterUrlGroup>
  	<excludeFilterUrl>http://10.162.1.17:8080/sp</excludeFilterUrl>
  </excludeFilterUrlGroup>
  <!--
  <sp:keystorePassword>sp:keystorePassword</sp:keystorePassword>
  -->
  <!-- 匹配servletpath的处理类 -->
  <samlhandlerGroup>
    <samlhandler id="SPLogin"><ref name="SAMLLoginhandler"/></samlhandler>
    <samlhandler id="SPAssertionConsumer"><ref name="SAMLAssertionConsumerHandler"/></samlhandler>
    <samlhandler id="SPLogout"><ref name="logouthandler"/></samlhandler>
    <samlhandler id="SPLogoutServiceSOAP"><ref name="logoutServiceSOAPhandler"/></samlhandler>
    <samlhandler id="SPLogoutConsumer"><ref name="samllogoutConsumer"/></samlhandler>
  </samlhandlerGroup>

<!-- login -->
<class id="SAMLLoginhandler" class="org.loushang.bsp.security.sp.service.process.impl.Loginhandler"/>
<!-- ACS -->
<class id="SAMLAssertionConsumerHandler" class="org.loushang.bsp.security.sp.service.process.impl.AssertionConsumerHandler">
	<property value="assertionValidator"><ref name="DefaultAssertionValidator"/></property>
	<property value="responseValidator"><ref name="DefaultResponseValidator"/></property>
	<property value="sessionHandler"><ref name="sessionHandler"/></property>
	<property value="forwordpath"><value>/jsp/b.jsp</value></property>
</class>
<!-- 处理IDP SOAP注销请求 -->
<class id="logoutServiceSOAPhandler" class="org.loushang.bsp.security.sp.service.process.impl.LogoutSOAPHandler">
	<property value="sessionHandler"><ref name="sessionHandler"/></property>
</class>

<!-- 注销 -->
<class id="logouthandler" class="org.loushang.bsp.security.sp.service.process.impl.LogoutHandler">
	<property value="sessionhandler"><ref name="sessionHandler"/></property>
	<property value="iLogout"><ref name="iLogout"/></property>
</class>

<class id="samllogoutConsumer" class="org.loushang.bsp.security.sp.service.process.impl.LogoutConsumerHandler">
	<property value="sessionhandler"><ref name="sessionHandler"/></property>
	<property value="iLogout"><ref name="iLogout"/></property>
</class>
<!-- 这个类需要配置为业务系统实现的类 -->
<class id="iLogout" class="org.loushang.bsp.security.sp.service.process.impl.Logout"/>
<!-- 注销 -->

<!-- 断言的验证类 -->
<class id="DefaultAssertionValidator" class="org.loushang.bsp.security.sp.component.validate.DefaultAssertionValidator"/>
<!-- response的验证类 -->
<class id="DefaultResponseValidator" class="org.loushang.bsp.security.sp.component.validate.DefaultResponseValidator"/>
<!-- 会话管理 -->
<class id="sessionHandler" class="org.loushang.bsp.security.sp.session.impl.DefaultSessionHandler"/>
</sp:spconfig>
